# Generated by Django 5.1.5 on 2025-02-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_buy_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
    ]
