# Generated by Django 5.1.5 on 2025-02-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_buydeswedding_buyinv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationcard',
            name='price',
        ),
    ]
