# Generated by Django 5.1.5 on 2025-02-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_invitationcard_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcard',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
