# Generated by Django 5.1.2 on 2025-03-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='buydeswedding',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyinv',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
